APP_TITLE = 'Type Racer'

VIRTUAL_WIDTH = 384
VIRTUAL_HEIGHT = 216

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

MAXIMUM_ERROR_ACCUMULATION_LENGTH = 4

-- ground tiles
GROUND_TILE_SIZE = 16

GROUND_GRASS_TILES = { 1, 2, 3 }
GROUND_PAVEMENT_TILES = { 4 }

GROUND_TILE_FLOWER = 5

GROUND_TILE_ROAD = 6

GROUND_GRASS_HEIGHT = 4
GROUND_PAVEMENT_HEIGHT = 2
