PLAYER = {
    name = 'you',
    driverId = 01,
    width = 32,
    height = 24,
    texture = 'cars',
    frames = { 1, 2 },
    tint = { 255, 170, 29 },
}

OPPONENTS = {
    -- bosses:
    -- level 2
    ['catwithblueeyes'] = {
        name = 'The Great Marina',
        driverId = 30,
        width = 32,
        height = 24,
        texture = 'cars',
        frames = { 1, 2 },
        speed = 95,
        tint = { 186, 175, 206 },
    },

    -- regular NPCs:
    -- level 1
    ["postman-bob"]= {
        name = "Postman Bob",
        driverId = 44,
        width = 24,
        height = 16,
        texture = "motos",
        frames = {5,6},
        speed = 55,
        tint = { 255, 255, 255 },
    },
    ["nr-jessica"]= {
        name = "Neighbour Jessica",
        driverId = 06,
        width = 24,
        height = 16,
        texture = "motos",
        frames = {3,4},
        speed = 85,
        tint = { 255, 255, 255 },
    },
    ["teddy-bear"]= {
        name = "Teddy Bear",
        driverId = 10,
        width = 24,
        height = 16,
        texture = "motos",
        frames = {1,2},
        speed = 60,
        tint = { 255, 255, 255 },
    },

    -- misc
    ['st235'] = {
        name = 'Alex D.',
        driverId = 37,
        width = 32,
        height = 24,
        texture = 'cars',
        frames = { 5, 6 },
        speed = 60,
        tint = { 255, 255, 255 },
    },
    ['goto'] = {
        name = 'Tia',
        driverId = 42,
        width = 32,
        height = 24,
        texture = 'cars',
        frames = { 15, 16 },
        speed = 60,
        tint = { 255, 255, 255 },
    },
    ['granny'] = {
        name = 'granny',
        driverId = 04,
        width = 32,
        height = 24,
        texture = 'cars',
        frames = { 9, 10 },
        speed = 120,
        tint = { 255, 255, 255 },
    },
    ['jd'] = {
        name = 'JD',
        driverId = 11,
        width = 32,
        height = 24,
        texture = 'cars',
        frames = { 1, 2 },
        speed = 240,
        tint = { 255, 255, 255 },
    },
    ['dracula'] = {
        name = 'Dr. Acula',
        driverId = 13,
        width = 32,
        height = 24,
        texture = 'cars',
        frames = { 3, 4 },
        speed = 180,
        tint = { 255, 255, 255 },
    },
    ['skipper'] = {
        name = 'Skipper',
        driverId = 44,
        width = 24,
        height = 16,
        texture = 'motos',
        frames = { 1, 2 },
        speed = 60,
        tint = { 255, 255, 255 },
    },
}
