PLAYER = {
    name = 'you',
    driverId = 01,
    width = 32,
    height = 24,
    texture = 'cars',
    frames = { 1, 2 },
    tint = { 255, 170, 29 },
}

OPPONENTS = {
    ['st235'] = {
        name = 'Alex D.',
        driverId = 37,
        width = 32,
        height = 24,
        texture = 'cars',
        frames = { 5, 6 },
        speed = 60,
        tint = { 255, 255, 255 },
    },
    ['goto'] = {
        name = 'Tia',
        driverId = 42,
        width = 32,
        height = 24,
        texture = 'cars',
        frames = { 15, 16 },
        speed = 60,
        tint = { 255, 255, 255 },
    },
    ['catwithblueeyes'] = {
        name = 'Marina',
        driverId = 30,
        width = 32,
        height = 24,
        texture = 'cars',
        frames = { 1, 2 },
        speed = 92,
        tint = { 186, 175, 206 },
    },
    ['granny'] = {
        name = 'granny',
        driverId = 04,
        width = 32,
        height = 24,
        texture = 'cars',
        frames = { 9, 10 },
        speed = 120,
        tint = { 255, 255, 255 },
    },
    ['jd'] = {
        name = 'JD',
        driverId = 11,
        width = 32,
        height = 24,
        texture = 'cars',
        frames = { 1, 2 },
        speed = 240,
        tint = { 255, 255, 255 },
    },
    ['dracula'] = {
        name = 'Dr. Acula',
        driverId = 13,
        width = 32,
        height = 24,
        texture = 'cars',
        frames = { 3, 4 },
        speed = 180,
        tint = { 255, 255, 255 },
    },
    ['skipper'] = {
        name = 'Skipper',
        driverId = 44,
        width = 24,
        height = 16,
        texture = 'motos',
        frames = { 1, 2 },
        speed = 60,
        tint = { 255, 255, 255 },
    },
}
